### PR TITLE
Added icon

### PR DESCRIPTION
**Pull request by deepesh16b**
@iamakhileshmishra @22shubh22 
I have added leetcode icon and modified a little font size and changed the background color from black to little dark grey, so that the logo will look good.

### CODE REVIEW

**Comment by iamakhileshmishra** [comment]
@deepesh16b Your PR has some merge conflicts better take a pull from the master before raising a PR. 
I am closing this PR and once you resolve the issue you can make the PR again

**Comment by deepesh16b** [comment]
Okay @iamakhileshmishra ,
but in the updated website, the api's are not working 
Screenshot 2022-10-08 114255

**Comment by deepesh16b** [comment]
@iamakhileshmishra 
Can you please remove the invalid tag, I think it may reject me from Hacktober fest

**Comment by iamakhileshmishra** [comment]
@deepesh16b It will not don't worry work on the other issue 

And for the API issue run npm i and install the moment dependency then go live it will work

**Pull request closed without merging**
